# -*- coding: utf-8 -*-
"""Polygon_Decomp

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CiXmbi7PIhZpMna5pTt3QNke3H5c9vdG
"""

from time import sleep
from shapely.geometry import Polygon
import matplotlib.pyplot as plt
import sys

cmdargs = sys.argv
print(cmdargs[1])

file = open(cmdargs[1],"r")
lines = file.readlines()

temp = []
curr = []
for a in lines:
    a = [x for x in a.strip().split(' ')]
    if(len(a) == 1):
        if(len(curr)>0):
            curr.append(curr[0])
            temp.append(curr)
        curr = []
    else:
        curr.append([float(a[0]),float(a[1])])

# polygon = [[15, 16], [13, 8], [9, 9], [4, 9],[0,8],[-5,5], [0,2], [2,-2], [6,-4], [10,-5], [15,-3], [17,0], [15,2], [10,2],[7,3], [10,5]]
convex_polygons = temp
print(temp)
fig, ax = plt.subplots()

for i, polygon in enumerate(convex_polygons):
    x_coords = [v[0] for v in polygon]
    y_coords = [v[1] for v in polygon]
    ax.set_aspect('auto')
    
    ax.fill(x_coords, y_coords, alpha=0.4, label=f'Face {i}')
    ax.plot(x_coords, y_coords, color='navy')
    plt.draw() 
    plt.pause(0.01)
    sleep(0.1)

ax.set_title('Convex Polygon Decomposition')
ax.legend()

plt.show()

